CONTRIBUTING.d/git: core.abbrev: Use 12 characters
This reverts 1bbec490379b (2026-02-26; "CONTRIBUTING.d/git: core.abbrev:
Use only 8 characters").

While 8 characters are unambiguous together with the date and subject,
there are colisions of the hash, which make it uncomfortable to use.
Let's raise it back to 12 characters, which adds some noise, but makes
it easier to use (no need to disambiguate; or at least not so often).

Here's a collision I found recently:

	$ git ref 8eea66b8
	error: short object ID 8eea66b8 is ambiguous
	hint: The candidates are:
	hint:   8eea66b82 commit 2025-06-06 - man/: SYNOPSIS: Don't highlight forward declarations of function parameters
	hint:   8eea66b8b commit 2019-11-16 - clone.2: Check for MAP_FAILED not NULL on mmap()
	fatal: ambiguous argument '8eea66b8': unknown revision or path not in the working tree.
	Use '--' to separate paths from revisions, like this:
	'git <command> [<revision>...] -- [<file>...]'

Fixes: 1bbec490379b (2026-02-26; "CONTRIBUTING.d/git: core.abbrev: Use only 8 characters")
Signed-off-by: Alejandro Colomar <alx@kernel.org>